// lang.js

export const texts = {
    sv: {
        heroSubtitle: "Student och Utvecklare",
        heroDesc: "Jag skapar moderna webbapplikationer med passion för användarupplevelse och ren kod.",
        seeProjects: "Se projekt",
        contactMe: "Kontakta mig",
        projects: "Egna Projekt",
        projectsDesc: "Utforska mina senaste projekt, klicka på korten för att läsa mer",
        project1Title: "Unifeed - Nyhetsflöde",
        project1Rating: "Top 1 AppStore Norge - Tidsskrifter och dagstidningar",
        project1Rating1: "Top 2 AppStore Norge - Nyheter", 
        project1Rating2: "Top 5 AppStore Sverige - Tidsskrifter och dagstidningar",
        project1Rating3: "Top 20 AppStore Sverige - Nyheter",
        project1Desc: "Universellt nyhetsflöde med fördefinierade RSS-flöden för olika nyhetskategorier, brottsplatskarta och svenska, norska och finska polisens nationella/lokala nyheter/aktiviteter.",
        project2Title: "Eloque AI",
        project2Desc: "Ladda och kör open-sourcade AI LLM-modeller helt lokalt på enhetens GPU (Apple Metal). Öppen källkod och finns tillgänglig på GitHub.",
        project3Title: "Univert – Enhetsomvandlare",
        project3Desc: "Universell enhetsomvandlare för iOS/macOS byggd med lokal konvertering och realtidsdata för valutor hämtade genom API från Europeiska Centralbanken. Öppen källkod finns på GitHub.",
        project4Title: "SwipeFlix",
        project4Desc: "Interaktiv Tinder-liknande swipe-funktion för att upptäcka och spara filmer och serier till watchlist. Upptäck nya filmer och serier från TMDB katalog hämtad via API. Öppen källkod finns på GitHub.",
        experience: "Arbetserfarenhet",
        experienceDesc: "Min professionella resa inom olika branscher",
        exp1Title: "Willys Västhaga, Örebro (Maj 2023 – Maj 2025)",
        exp1Role: "Butiksbiträde",
        exp1Desc: "Deltidstjänst med jourbefattning, kassa och e-handel parallellt med studier. Heltid under somrarna.",
        exp2Title: "Volvo On Demand / Ungdomskraft, Stockholm (Okt. 2020 – Jan. 2022)",
        exp2Role: "Team Leader - Koordinator",
        exp2Desc: "Ledde ett team på fem personer, ansvarade för bemanning och koordinering av arbetsuppgifter, fältarbete och hantering av bilflotta åt Volvo On Demand (fd. Volvo Car Mobility).",
        exp3Title: "Coop Torsvik, Stockholm (Jan. 2018 – Dec. 2020)",
        exp3Role: "Butiksbiträde",
        exp3Desc: "Deltidstjänst med jourbefattning, kassa och kundservice. Heltid under somrarna.",
        education: "Utbildning",
        educationDesc1: "Universitet",
        educationDesc2: "Gymnasium",
        edu1Title: "Handelshögskolan vid Örebro Universitet (2022 - 2025)",
        edu1Title1: "Kandidatexamen i nationalekonomi",
        edu1Desc: "Ekonomiprogrammet med inriktning mot nationalekonomi (mikro- och makroekonomi).",
        edu2Title: "Handelshögskolan vid Örebro Universitet (2022 - 2025)",
        edu2Title1: "Kandidatexamen i systemvetenskap",
        edu2Desc: "Systemvetenskapliga programmet med inriktning mot programutveckling.",
        edu3Title: "Hersby Gymnasium (2017 – 2020)",
        edu3Desc: "Ekonomiprogrammet med inriktning mot juridik",
        contact: "Kontakta mig",
        resume: "Curriculum Vitae",
        protokoll: "Protokoll:",
        arkitekturer: "Arkitekturer:",
        utmärkelser: "Utmärkelser:",
    },
    en: {
        heroSubtitle: "Fullstack Developer",
        heroDesc: "I create modern web applications with a passion for user experience and clean code.",
        seeProjects: "View Projects",
        contactMe: "Contact Me",
        projects: "Projects",
        projectsDesc: "Explore my latest projects, click on the cards to read more",
        project1Title: "Unifeed - News Feed",
        project1Rating: "Top 1 AppStore Norway - Magazines and Newspapers",
        project1Rating1: "Top 2 AppStore Norway - News",
        project1Rating2: "Top 5 AppStore Sweden - Magazines and Newspapers",
        project1Rating3: "Top 20 AppStore Sweden - News",
        project1Desc: "Premade RSS Feeds for different news categories, crime scene maps, and Swedish, Norwegian, and Finnish police national/local news/activity feeds.",
        project2Title: "Eloque AI",
        project2Desc: "Run LLM's locally on iOS, iPadOS and MacOS (ARM). Choose between different models and quantizations to your liking.",
        project3Title: "Univert – Unit Converter",
        project3Desc: "Universal unit converter for iOS/macOS built in SwiftUI with offline logic and real-time currency rates fetched through API from European Central Bank. Open source available on GitHub.",
        project4Title: "SwipeFlix",
        project4Desc: "Interactive swipe feature for discovering and saving movies and series to watchlist. Discover new movies and series from TMDB catalog fetched via API. Open source available on GitHub.",
        experienceDesc: "My professional journey across various fields",
        exp1Title: "Willys Västhaga, Örebro (May 2023 – May 2025)",
        exp1Role: "Store Assistant",
        exp1Desc: "Part-time work with on-call duties, cashier and e-commerce parallel to studies. Full-time during summers.",
        exp2Title: "Volvo On Demand / Ungdomskraft, Stockholm (Oct. 2020 – Jan. 2022)",
        exp2Role: "Team Leader - Coordinator",
        exp2Desc: "Led a team of five, responsible for staffing, coordination, field work and fleet management for Volvo On Demand (formerly Volvo Car Mobility).",
        exp3Title: "Coop Torsvik, Stockholm (Jan. 2018 – Dec. 2020)",
        exp3Role: "Store Assistant",
        exp3Desc: "Part-time work with on-call duties, cashier and customer service. Full-time during summers.",
        education: "Education",
        experience: "Work experience",
        educationDesc1: "University",
        educationDesc2: "Upper Secondary School",
        edu1Title: "Örebro University School of Business (2022 – 2025)",
        edu1Title1: "Bachelor's Degree in Economics",
        edu1Desc: "Economics programme with a focus on microeconomics and macroeconomics.",
        edu2Title: "Örebro University School of Business (2022 – 2025)",
        edu2Title1: "Bachelor's Degree in Informatics (System Science)",
        edu2Desc: "Informatics programme with a focus on software development.",
        edu3Title: "Hersby Gymnasium (2017 – 2020)",
        edu3Desc: "Economics programme with a focus on law.",
        contact: "Contact Me",
        resume: "Curriculum Vitae",
        protokoll: "Protocol",
        arkitekturer: "Architectures:",
        utmärkelser: "Awards:",
    }
};
