// lang.js

export const texts = {
    sv: {
        heroSubtitle: "Fullstack Utvecklare",
        heroDesc: "Jag skapar moderna webbapplikationer med passion för användarupplevelse och ren kod.",
        seeProjects: "Se projekt",
        contactMe: "Kontakta mig",
        projects: "Egna Projekt",
        projectsDesc: "Utforska mina senaste projekt, klicka på korten för att läsa mer",
        project1Title: "Unifeed - Nyhetsflöde",
        project1Rating: "Top 1 på AppStore Norge - Tidsskrifter och dagstidningar",
        project1Rating1: "Top 2 på AppStore Norge - Nyheter", 
        project1Rating2: "Top 5 på AppStore Sverige - Tidsskrifter och dagstidningar",
        project1Rating3: "Top 20 på AppStore Sverige - Nyheter",
        project1Desc: "Universellt nyhetsflöde med fördefinierade RSS-flöden för olika nyhetskategorier, brottsplatskarta och svenska, norska och finska polisens nationella/lokala nyheter/aktiviteter.",
        project2Title: "Eloque AI",
        project2Desc: "Ladda och kör open-sourcade AI LLM-modeller helt lokalt på enhetens GPU (Apple Metal). Öppen källkod och finns tillgänglig på GitHub.",
        project3Title: "Univert – Enhetsomvandlare",
        project3Desc: "Universell enhetsomvandlare för iOS/macOS byggd med lokal konvertering och realtidsdata för valutor hämtade genom API från Europeiska Centralbanken.",
        project4Title: "SwipeFlix",
        project4Desc: "Interaktiv Tinder-liknande swipe-funktion för att upptäcka och spara filmer och serier till watchlist. Upptäck nya filmer och serier från TMDB katalog hämtad via API.",
        experience: "Arbetserfarenhet",
        experienceDesc: "Min professionella resa inom olika branscher",
        exp1Title: "Butiksbiträde – Willys Västhaga, Örebro (2023–2025)",
        exp1Desc: "Deltidstjänst med jouransvar, kassa och e-handel. Heltid under somrarna.",
        exp2Title: "Team Leader – Ungdomskraft / Volvo On Demand, Stockholm (2020–2022)",
        exp2Desc: "Ledde ett team på fem personer, ansvarade för bemanning, fältarbete och hantering av bilflotta åt Volvo On Demand.",
        exp3Title: "Butiksbiträde – Coop Torsvik, Stockholm (2018–2020)",
        exp3Desc: "Jourbefattning, kassa och kundservice. Heltid under somrarna.",
        education: "Utbildning",
        educationDesc: "Min akademiska bakgrund och kontinuerliga lärande",
        edu1Title: "Handelshögskolan vid Örebro Universitet (2022–2025)",
        edu1Desc: "Dubbelkandidat: Systemvetenskap (Informatik) och Nationalekonomi. Inriktning mot programutveckling.",
        contact: "Kontakta mig",
        resume: "CV",
        protokoll: "Protokoll:",
        arkitekturer: "Arkitekturer:",
    },
    en: {
        heroSubtitle: "Fullstack Developer",
        heroDesc: "I create modern web applications with a passion for user experience and clean code.",
        seeProjects: "View Projects",
        contactMe: "Contact Me",
        projects: "Projects",
        projectsDesc: "Explore my latest projects, click on the cards to read more",
        project1Title: "Unifeed - News Feed",
        project1Desc: "Premade RSS Feeds for different news categories, crime scene maps, and Swedish, Norwegian, and Finnish police national/local news/activity feeds.",
        project2Title: "Eloque AI",
        project2Desc: "Run LLM's locally on iOS, iPadOS and MacOS (ARM). Choose between different models and quantizations to your liking.",
        project3Title: "Univert – Unit Converter",
        project3Desc: "Universal unit converter for iOS/macOS built in SwiftUI with offline logic and real-time currency rates fetched through API from European Central Bank.",
        project4Title: "SwipeFlix",
        project4Desc: "Interactive swipe feature for discovering and saving movies and series to watchlist. Discover new movies and series from TMDB catalog fetched via API.",
        experienceDesc: "My professional journey across various fields",
        exp1Title: "Store Assistant – Willys Västhaga, Örebro (2023–2025)",
        exp1Desc: "Part-time with on-call duties, checkout and e-commerce. Full-time during summers.",
        exp2Title: "Team Leader – Ungdomskraft / Volvo On Demand, Stockholm (2020–2022)",
        exp2Desc: "Led a team of five, responsible for staffing, field work and fleet management for Volvo On Demand.",
        exp3Title: "Store Assistant – Coop Torsvik, Stockholm (2018–2020)",
        exp3Desc: "On-call duties, cashier and customer service. Full-time during summers.",
        education: "Education",
        educationDesc: "My academic background and continuous learning",
        edu1Title: "Örebro University School of Business (2022–2025)",
        edu1Desc: "Double bachelor's: Informatics (System Science) and Economics. Focus on software development.",
        contact: "Contact Me",
        resume: "CV",
        protokoll: "Protocol",
        arkitekturer: "Architectures:",
    }
};
