// lang.js

export const texts = {
    sv: {
        heroSubtitle: "Fullstack Utvecklare",
        heroDesc: "Jag skapar moderna webbapplikationer med passion för användarupplevelse och ren kod.",
        seeProjects: "Se projekt",
        contactMe: "Kontakta mig",
        projects: "Egna Projekt",
        projectsDesc: "Utforska mina senaste projekt och tekniska lösningar",
        project1Title: "E-handelslösning",
        project1Desc: "Modern e-handelsplattform byggd med React och Node.js",
        project2Title: "Task Manager App",
        project2Desc: "Responsiv app för projekthantering med realtidsuppdateringar",
        project3Title: "Portfolio Dashboard",
        project3Desc: "Interaktiv dashboard för att visa projektstatistik",
        experience: "Arbetserfarenhet",
        experienceDesc: "Min professionella resa inom webbutveckling",
        exp1Title: "Senior Utvecklare – Tech Solutions AB (2022 - Nuvarande)",
        exp1Desc: "Ledande utvecklare för moderna webbapplikationer med fokus på användarupplevelse.",
        exp2Title: "Frontend Utvecklare – Digital Agency (2020 - 2022)",
        exp2Desc: "Utvecklade responsiva webbsidor och applikationer för olika kunder.",
        exp3Title: "Junior Utvecklare – StartUp Inc (2018 - 2020)",
        exp3Desc: "Första professionella rollen där jag lärde mig moderna utvecklingsmetoder.",
        education: "Utbildning",
        educationDesc: "Min akademiska bakgrund och kontinuerliga lärande",
        edu1Title: "Kandidatexamen i Datavetenskap – KTH (2015 - 2018)",
        edu1Desc: "Specialisering inom webbutveckling och mjukvarudesign.",
        edu2Title: "Fullstack Bootcamp – Coding Academy (2018)",
        edu2Desc: "Intensiv kurs i modern webbutveckling och agila metoder.",
        contact: "Kontakta mig",
        resume: "CV",
    },
    en: {
        heroSubtitle: "Fullstack Developer",
        heroDesc: "I create modern web applications with a passion for user experience and clean code.",
        seeProjects: "View Projects",
        contactMe: "Contact Me",
        projects: "Projects",
        projectsDesc: "Explore my latest projects and technical solutions",
        project1Title: "E-commerce Solution",
        project1Desc: "Modern e-commerce platform built with React and Node.js",
        project2Title: "Task Manager App",
        project2Desc: "Responsive project management app with real-time updates",
        project3Title: "Portfolio Dashboard",
        project3Desc: "Interactive dashboard to display project statistics",
        experience: "Experience",
        experienceDesc: "My professional journey in web development",
        exp1Title: "Senior Developer – Tech Solutions AB (2022 - Present)",
        exp1Desc: "Lead developer for modern web applications focused on UX.",
        exp2Title: "Frontend Developer – Digital Agency (2020 - 2022)",
        exp2Desc: "Developed responsive websites and applications for various clients.",
        exp3Title: "Junior Developer – StartUp Inc (2018 - 2020)",
        exp3Desc: "First professional role where I learned modern dev methods.",
        education: "Education",
        educationDesc: "My academic background and continuous learning",
        edu1Title: "Bachelor's in Computer Science – KTH (2015 - 2018)",
        edu1Desc: "Specialized in web development and software design.",
        edu2Title: "Fullstack Bootcamp – Coding Academy (2018)",
        edu2Desc: "Intensive course in modern web development and agile methods.",
        contact: "Contact Me",
        resume: "CV",
        cta: "© 2025 Adrian Neshad"
    }
};
